"""
AI-NIDS
PHASE 10.6 — CONFIDENCE & THRESHOLD ANALYSIS

Compatible with prediction results generated by test_prediction.py

Expected prediction file columns:
    Actual_Binary
    Predicted_Binary
    Actual_Attack_Type
    Predicted_Attack_Type
    Confidence
"""

import os
import sys
import json
import numpy as np
import pandas as pd


# ============================================================================
# PATH CONFIGURATION
# ============================================================================

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PREDICTION_FILE = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "prediction_results",
    "test_predictions.csv"
)

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "data",
    "processed",
    "confidence_analysis"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================================
# DISPLAY HELPERS
# ============================================================================

WIDTH = 70


def separator(char="="):
    print(char * WIDTH)


def section(title):
    print()
    separator()
    print(title)
    separator()


# ============================================================================
# START
# ============================================================================

print("=" * WIDTH)
print("PHASE 10.6 — CONFIDENCE & THRESHOLD ANALYSIS")
print("=" * WIDTH)


# ============================================================================
# STEP 1 — CHECK PREDICTION FILE
# ============================================================================

section("STEP 1 — LOADING PREDICTION RESULTS")

print("Loading prediction results...")
print(PREDICTION_FILE)

if not os.path.exists(PREDICTION_FILE):
    print()
    print("❌ Prediction file not found!")
    print()
    print("Expected:")
    print(PREDICTION_FILE)
    sys.exit(1)


try:
    df = pd.read_csv(PREDICTION_FILE)
except Exception as e:
    print()
    print("❌ Failed to load prediction file.")
    print("Error:", e)
    sys.exit(1)


print(f"Prediction dataset shape: {df.shape}")


# ============================================================================
# STEP 2 — CHECK COLUMNS
# ============================================================================

section("STEP 2 — CHECKING REQUIRED COLUMNS")

required_columns = [
    "Actual_Binary",
    "Predicted_Binary",
    "Actual_Attack_Type",
    "Predicted_Attack_Type",
    "Confidence"
]

print("AVAILABLE COLUMNS")

for column in df.columns:
    print(f" - {column}")


missing_columns = [
    column for column in required_columns
    if column not in df.columns
]


if missing_columns:

    print()
    print("❌ Missing required columns:")

    for column in missing_columns:
        print(f" - {column}")

    print()
    print("Available columns:")
    print(list(df.columns))

    raise ValueError(
        "\nPrediction file does not contain the required columns."
    )


print()
print("✅ All required columns found.")


# ============================================================================
# STEP 3 — CLEAN / VALIDATE CONFIDENCE
# ============================================================================

section("STEP 3 — VALIDATING CONFIDENCE VALUES")

df["Confidence"] = pd.to_numeric(
    df["Confidence"],
    errors="coerce"
)

invalid_confidence = df["Confidence"].isna().sum()

if invalid_confidence > 0:

    print(
        f"⚠️ Invalid confidence values found: "
        f"{invalid_confidence}"
    )

    df = df.dropna(subset=["Confidence"]).copy()

    print(
        f"Rows remaining after removing invalid confidence: "
        f"{len(df):,}"
    )


# Confidence should normally be between 0 and 1.

out_of_range = (
    (df["Confidence"] < 0) |
    (df["Confidence"] > 1)
).sum()


if out_of_range > 0:

    print(
        f"⚠️ Confidence values outside [0, 1]: "
        f"{out_of_range}"
    )

    print("Clipping confidence values to [0, 1].")

    df["Confidence"] = df["Confidence"].clip(0, 1)


print("✅ Confidence values validated.")


# ============================================================================
# STEP 4 — BASIC CONFIDENCE STATISTICS
# ============================================================================

section("CONFIDENCE STATISTICS")

confidence = df["Confidence"]

print(f"Minimum confidence : {confidence.min():.6f}")
print(f"Maximum confidence : {confidence.max():.6f}")
print(f"Mean confidence    : {confidence.mean():.6f}")
print(f"Median confidence  : {confidence.median():.6f}")
print(f"Std deviation      : {confidence.std():.6f}")


# ============================================================================
# STEP 5 — CONFIDENCE DISTRIBUTION
# ============================================================================

section("CONFIDENCE DISTRIBUTION")

bins = [
    0.0,
    0.50,
    0.60,
    0.70,
    0.80,
    0.90,
    0.95,
    0.99,
    1.000001
]

labels = [
    "< 50%",
    "50-60%",
    "60-70%",
    "70-80%",
    "80-90%",
    "90-95%",
    "95-99%",
    "99-100%"
]

confidence_categories = pd.cut(
    confidence,
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

distribution = (
    confidence_categories
    .value_counts(sort=False)
)


for label, count in distribution.items():

    percentage = (
        count / len(df) * 100
        if len(df) > 0
        else 0
    )

    print(
        f"{str(label):<10}: "
        f"{count:>8,} "
        f"({percentage:.4f}%)"
    )


# ============================================================================
# STEP 6 — CREATE CORRECTNESS FLAGS
# ============================================================================

section("STEP 6 — CALCULATING CORRECT / INCORRECT PREDICTIONS")

# Binary correctness

df["Binary_Correct"] = (
    df["Actual_Binary"].astype(str).str.upper()
    ==
    df["Predicted_Binary"].astype(str).str.upper()
)


# Multi-class correctness

df["Multiclass_Correct"] = (
    df["Actual_Attack_Type"].astype(str)
    ==
    df["Predicted_Attack_Type"].astype(str)
)


binary_correct = int(df["Binary_Correct"].sum())
binary_incorrect = int((~df["Binary_Correct"]).sum())

multi_correct = int(df["Multiclass_Correct"].sum())
multi_incorrect = int((~df["Multiclass_Correct"]).sum())


# ============================================================================
# STEP 7 — CORRECT VS INCORRECT CONFIDENCE
# ============================================================================

section("CORRECT VS INCORRECT CONFIDENCE")

print("Binary:")

if binary_correct > 0:
    print(
        f"Correct mean confidence: "
        f"{df.loc[df['Binary_Correct'], 'Confidence'].mean():.6f}"
    )

if binary_incorrect > 0:
    print(
        f"Incorrect mean confidence: "
        f"{df.loc[~df['Binary_Correct'], 'Confidence'].mean():.6f}"
    )
else:
    print("Incorrect mean confidence: N/A")

print()

print("Multi-class:")

if multi_correct > 0:
    print(
        f"Correct mean confidence: "
        f"{df.loc[df['Multiclass_Correct'], 'Confidence'].mean():.6f}"
    )

if multi_incorrect > 0:
    print(
        f"Incorrect mean confidence: "
        f"{df.loc[~df['Multiclass_Correct'], 'Confidence'].mean():.6f}"
    )
else:
    print("Incorrect mean confidence: N/A")


# ============================================================================
# STEP 8 — BINARY ERROR ANALYSIS
# ============================================================================

section("BINARY ERROR ANALYSIS")

actual_binary = (
    df["Actual_Binary"]
    .astype(str)
    .str.upper()
)

predicted_binary = (
    df["Predicted_Binary"]
    .astype(str)
    .str.upper()
)


# Try to support both numeric and text labels.

actual_attack = actual_binary.isin(
    ["1", "ATTACK", "TRUE"]
)

predicted_attack = predicted_binary.isin(
    ["1", "ATTACK", "TRUE"]
)

false_positive_mask = (
    (~actual_attack)
    &
    predicted_attack
)

false_negative_mask = (
    actual_attack
    &
    (~predicted_attack)
)

false_positive_count = int(false_positive_mask.sum())
false_negative_count = int(false_negative_mask.sum())

print(f"False Positives: {false_positive_count:,}")
print(f"False Negatives: {false_negative_count:,}")


if false_positive_count > 0:

    fp_conf = df.loc[
        false_positive_mask,
        "Confidence"
    ]

    print(
        f"False Positive mean confidence: "
        f"{fp_conf.mean():.6f}"
    )

    print(
        f"False Positive maximum confidence: "
        f"{fp_conf.max():.6f}"
    )

else:

    print("False Positive mean confidence: N/A")
    print("False Positive maximum confidence: N/A")


if false_negative_count > 0:

    fn_conf = df.loc[
        false_negative_mask,
        "Confidence"
    ]

    print(
        f"False Negative mean confidence: "
        f"{fn_conf.mean():.6f}"
    )

    print(
        f"False Negative maximum confidence: "
        f"{fn_conf.max():.6f}"
    )

else:

    print("False Negative mean confidence: N/A")
    print("False Negative maximum confidence: N/A")


# ============================================================================
# STEP 9 — MULTI-CLASS ERROR ANALYSIS
# ============================================================================

section("MULTI-CLASS ERROR ANALYSIS")

multi_error_mask = ~df["Multiclass_Correct"]

print(
    f"Total multi-class errors: "
    f"{multi_error_mask.sum():,}"
)


if multi_error_mask.sum() > 0:

    multi_error_conf = df.loc[
        multi_error_mask,
        "Confidence"
    ]

    print(
        f"Mean confidence on errors: "
        f"{multi_error_conf.mean():.6f}"
    )

    print(
        f"Maximum confidence on errors: "
        f"{multi_error_conf.max():.6f}"
    )

else:

    print("Mean confidence on errors: N/A")
    print("Maximum confidence on errors: N/A")


# ============================================================================
# STEP 10 — PREDICTED ATTACK ANALYSIS
# ============================================================================

section("ATTACK CONFIDENCE")

predicted_attack_mask = predicted_attack

predicted_attack_count = int(
    predicted_attack_mask.sum()
)

print(
    f"Predicted attacks: "
    f"{predicted_attack_count:,}"
)


if predicted_attack_count > 0:

    attack_confidence = df.loc[
        predicted_attack_mask,
        "Confidence"
    ]

    print(
        f"Mean attack confidence: "
        f"{attack_confidence.mean():.6f}"
    )

    print(
        f"Minimum attack confidence: "
        f"{attack_confidence.min():.6f}"
    )

    print(
        f"Maximum attack confidence: "
        f"{attack_confidence.max():.6f}"
    )

else:

    print("Mean attack confidence: N/A")
    print("Minimum attack confidence: N/A")
    print("Maximum attack confidence: N/A")


# ============================================================================
# STEP 11 — ACTUAL ATTACK ANALYSIS
# ============================================================================

section("ACTUAL ATTACK CONFIDENCE")

actual_attack_count = int(
    actual_attack.sum()
)

print(
    f"Actual attacks in test set: "
    f"{actual_attack_count:,}"
)


if actual_attack_count > 0:

    actual_attack_confidence = df.loc[
        actual_attack,
        "Confidence"
    ]

    print(
        f"Mean confidence on actual attacks: "
        f"{actual_attack_confidence.mean():.6f}"
    )

    print(
        f"Minimum confidence on actual attacks: "
        f"{actual_attack_confidence.min():.6f}"
    )

    print(
        f"Maximum confidence on actual attacks: "
        f"{actual_attack_confidence.max():.6f}"
    )


# ============================================================================
# STEP 12 — THRESHOLD ANALYSIS
# ============================================================================

section("CONFIDENCE THRESHOLD ANALYSIS")

thresholds = [
    0.50,
    0.60,
    0.70,
    0.80,
    0.90,
    0.95,
    0.99
]

threshold_results = []


for threshold in thresholds:

    selected_mask = (
        df["Confidence"] >= threshold
    )

    selected = df.loc[selected_mask]

    sample_count = len(selected)

    coverage = (
        sample_count / len(df)
        if len(df) > 0
        else 0
    )

    if sample_count > 0:

        binary_accuracy = (
            selected["Binary_Correct"].mean()
        )

        multiclass_accuracy = (
            selected["Multiclass_Correct"].mean()
        )

    else:

        binary_accuracy = np.nan
        multiclass_accuracy = np.nan


    selected_predicted_attack = (
        predicted_attack_mask
        &
        selected_mask
    ).sum()


    selected_actual_attack = (
        actual_attack
        &
        selected_mask
    ).sum()


    result = {
        "Threshold": threshold,
        "Samples": sample_count,
        "Coverage": coverage,
        "Binary_Accuracy": binary_accuracy,
        "Multiclass_Accuracy": multiclass_accuracy,
        "Predicted_Attacks": int(
            selected_predicted_attack
        ),
        "Actual_Attacks": int(
            selected_actual_attack
        )
    }

    threshold_results.append(result)


    print()
    print(
        f"Threshold >= {threshold:.2f}"
    )

    print(
        f"  Samples: "
        f"{sample_count:,}"
    )

    print(
        f"  Coverage: "
        f"{coverage * 100:.4f}%"
    )

    if not np.isnan(binary_accuracy):

        print(
            f"  Binary accuracy: "
            f"{binary_accuracy:.6f}"
        )

        print(
            f"  Multi-class accuracy: "
            f"{multiclass_accuracy:.6f}"
        )

    else:

        print("  Binary accuracy: N/A")
        print("  Multi-class accuracy: N/A")

    print(
        f"  Predicted attacks: "
        f"{int(selected_predicted_attack):,}"
    )

    print(
        f"  Actual attacks: "
        f"{int(selected_actual_attack):,}"
    )


threshold_df = pd.DataFrame(
    threshold_results
)


# ============================================================================
# STEP 13 — CLASS-WISE CONFIDENCE ANALYSIS
# ============================================================================

section("CLASS-WISE CONFIDENCE ANALYSIS")

class_results = []

for attack_type, group in df.groupby(
    "Actual_Attack_Type"
):

    total = len(group)

    correct = int(
        group["Multiclass_Correct"].sum()
    )

    incorrect = total - correct

    class_result = {
        "Class": attack_type,
        "Samples": total,
        "Correct": correct,
        "Incorrect": incorrect,
        "Accuracy": (
            correct / total
            if total > 0
            else np.nan
        ),
        "Mean_Confidence": group[
            "Confidence"
        ].mean(),
        "Median_Confidence": group[
            "Confidence"
        ].median(),
        "Min_Confidence": group[
            "Confidence"
        ].min(),
        "Max_Confidence": group[
            "Confidence"
        ].max()
    }

    class_results.append(class_result)


class_confidence_df = pd.DataFrame(
    class_results
)

class_confidence_df = class_confidence_df.sort_values(
    by="Samples",
    ascending=False
)


print(
    class_confidence_df.to_string(
        index=False
    )
)


# ============================================================================
# STEP 14 — ERROR DETAILS
# ============================================================================

section("ERROR SUMMARY")

error_summary = pd.DataFrame({
    "Metric": [
        "Total samples",
        "Binary correct",
        "Binary incorrect",
        "Binary accuracy",
        "Multi-class correct",
        "Multi-class incorrect",
        "Multi-class accuracy",
        "False positives",
        "False negatives",
        "Predicted attacks",
        "Actual attacks"
    ],
    "Value": [
        len(df),
        binary_correct,
        binary_incorrect,
        (
            binary_correct / len(df)
            if len(df) > 0
            else np.nan
        ),
        multi_correct,
        multi_incorrect,
        (
            multi_correct / len(df)
            if len(df) > 0
            else np.nan
        ),
        false_positive_count,
        false_negative_count,
        predicted_attack_count,
        actual_attack_count
    ]
})


print(
    error_summary.to_string(
        index=False
    )
)


# ============================================================================
# STEP 15 — SAVE THRESHOLD ANALYSIS
# ============================================================================

section("SAVING ANALYSIS RESULTS")

threshold_file = os.path.join(
    OUTPUT_DIR,
    "threshold_analysis.csv"
)

threshold_df.to_csv(
    threshold_file,
    index=False
)

print("Threshold analysis saved:")
print(threshold_file)


# ============================================================================
# STEP 16 — SAVE CLASS CONFIDENCE
# ============================================================================

class_confidence_file = os.path.join(
    OUTPUT_DIR,
    "class_confidence_analysis.csv"
)

class_confidence_df.to_csv(
    class_confidence_file,
    index=False
)

print()
print("Class confidence analysis saved:")
print(class_confidence_file)


# ============================================================================
# STEP 17 — SAVE ERROR SUMMARY
# ============================================================================

error_summary_file = os.path.join(
    OUTPUT_DIR,
    "error_summary.csv"
)

error_summary.to_csv(
    error_summary_file,
    index=False
)

print()
print("Error summary saved:")
print(error_summary_file)


# ============================================================================
# STEP 18 — SAVE CONFIDENCE SUMMARY
# ============================================================================

confidence_summary = {
    "total_samples": int(len(df)),

    "minimum_confidence": float(
        confidence.min()
    ),

    "maximum_confidence": float(
        confidence.max()
    ),

    "mean_confidence": float(
        confidence.mean()
    ),

    "median_confidence": float(
        confidence.median()
    ),

    "std_confidence": float(
        confidence.std()
    ),

    "binary_correct": binary_correct,

    "binary_incorrect": binary_incorrect,

    "binary_accuracy": float(
        binary_correct / len(df)
    ) if len(df) > 0 else None,

    "multiclass_correct": multi_correct,

    "multiclass_incorrect": multi_incorrect,

    "multiclass_accuracy": float(
        multi_correct / len(df)
    ) if len(df) > 0 else None,

    "false_positives": false_positive_count,

    "false_negatives": false_negative_count,

    "predicted_attacks": predicted_attack_count,

    "actual_attacks": actual_attack_count,

    "confidence_column": "Confidence",

    "prediction_file": PREDICTION_FILE
}


confidence_summary_file = os.path.join(
    OUTPUT_DIR,
    "confidence_summary.json"
)

with open(
    confidence_summary_file,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        confidence_summary,
        f,
        indent=4
    )


print()
print("Confidence summary saved:")
print(confidence_summary_file)


# ============================================================================
# STEP 19 — FINAL VALIDATION
# ============================================================================

section("FINAL VALIDATION")

validation_passed = True


if len(df) == 0:

    print("❌ Prediction dataset is empty.")
    validation_passed = False


if df["Confidence"].isna().any():

    print("❌ Missing confidence values found.")
    validation_passed = False


if (
    (df["Confidence"] < 0).any()
    or
    (df["Confidence"] > 1).any()
):

    print("❌ Invalid confidence range found.")
    validation_passed = False


if (
    df["Actual_Binary"].isna().any()
    or
    df["Predicted_Binary"].isna().any()
):

    print("❌ Missing binary predictions found.")
    validation_passed = False


if (
    df["Actual_Attack_Type"].isna().any()
    or
    df["Predicted_Attack_Type"].isna().any()
):

    print("❌ Missing multi-class predictions found.")
    validation_passed = False


if validation_passed:

    print("✅ Prediction file validated.")
    print("✅ Confidence values validated.")
    print("✅ Binary prediction analysis completed.")
    print("✅ Multi-class prediction analysis completed.")
    print("✅ Threshold analysis completed.")
    print("✅ Class-wise confidence analysis completed.")


# ============================================================================
# FINAL
# ============================================================================

print()
print("=" * WIDTH)

if validation_passed:

    print("✅ PHASE 10.6 COMPLETED SUCCESSFULLY")
    print()
    print("Confidence analysis completed.")

else:

    print("❌ PHASE 10.6 FAILED VALIDATION")

print("=" * WIDTH)

print()
print("Results directory:")
print(OUTPUT_DIR)